<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deleteInactiveClient_moveAccountFromOneClientToAnother" nsURI="http://cdapackage/deleteInactiveClient/moveAccountFromOneClientToAnother/DeleteConflictReason"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#21_18:Client#">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=client _ toClient->toClient"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="20_16:Bank">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#clients#" eType="#//%2321_18%3AClient%23"/>
  </eClassifiers>
</ecore:EPackage>
