<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="removeManagerFromClient_removeManagerFromClient" nsURI="http://cdapackage/removeManagerFromClient/removeManagerFromClient/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="15_15:Manager">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=manager _ manager"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#clients#" eType="#/0/14_14%3AClient"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="14_14:Client">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=client _ client"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="removeManagerFromClient_removeManagerFromClient" nsURI="http://cdapackage/removeManagerFromClient/removeManagerFromClient/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="15_15:Manager">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=manager _ manager"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#clients#" eType="#/1/14_14%3AClient"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="14_14:Client">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=client _ client"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
