<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteAccount_moveAccountFromOneClientToAnother" nsURI="http://cdapackage/deleteAccount/moveAccountFromOneClientToAnother/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|3|_|7|:Account#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#owner#" eType="#/0/|0|_|5|%3AClient"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|0|_|5|:Client">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=client _ fromClient->fromClient"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|1|_|4|:Bank">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#accounts#" eType="#/0/%23|3|_|7|%3AAccount%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="moveAccountFromOneClientToAnother_deleteAccount" nsURI="http://cdapackage/moveAccountFromOneClientToAnother/deleteAccount/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|7|_|3|:Account">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#owner#" eType="#/1/|5|_|0|%3AClient"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|5|_|0|:Client">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=fromClient _ client->client"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
