<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteInactiveClient_deleteInactiveClient" nsURI="http://cdapackage/deleteInactiveClient/deleteInactiveClient/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#21_21:Client#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=client _ client"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="20_20:Bank">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#clients#" eType="#/0/%2321_21%3AClient%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deleteInactiveClient_deleteInactiveClient" nsURI="http://cdapackage/deleteInactiveClient/deleteInactiveClient/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#21_21:Client#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=client _ client"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="20_20:Bank">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#clients#" eType="#/1/%2321_21%3AClient%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
